### ISSUE TITLE
Gripper

### ISSUE THREAD

**Issue by zumpchke** [LiciaHe/threadPlotter#1]
I don't get how you used the gripper frame.
 From the pictures, it doesn't look like fabric is being suspended on this at all.

Can you please clarify?

**Comment by LiciaHe** [comment]
Sure. Gripper frames are like photo frames. They are hollow rectangular blocks. The fabric is attached to the frame with nails but you can imagine it as gluing a piece of fabric to the top of a paper frame.  And this frame has a particular deep frame depth. The hollow area of the frame does not have any solid backing, thus allowing us to punch a needle through.  It might be helpful to take a  look at figure 1 of our paper: http://www.cond.org/punchneedle.pdf which is an overview of the entire setup.
